# Site
name: "This is Stan"
title: "This is Stan"
description: "I had some things to share."
logo: 'assets/images/pig-nose.png'
favicon: 'assets/images/pig-nose.png'
baseurl: ''
url: 'stan.boyet.me'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  stan:
    name: Stan
    display_name: Stan
    # avatar: 'assets/images/avatar.png'
    gravatar: 'f49ae44285e47fcdc21eac00206002a9ba98a098147476aa9b475e088a012f0b'
    email: stan+blog@boyet.me
    # web: https://stanislas.boyet.me
    twitter: https://twitter.com/stanboyet
    description: "Hi, this is Stan."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
